---
- name: Sample Email Playbook  
  hosts: "all
  tasks:
    mail:
    #host: app-smtp-exchange.uk.hsbc
    subject: Test Email playbook
    body: "hi from sayali"
    from: "sayalijoshi678@gmail.com"  
    to: "ahuchcha@redhat.com" 
      
