---
- name: Sample Email Playbook  
  hosts: all
  vars: 
     password:
     #full_name:
  tasks:
    - mail:
        host: localhost
        subject: Test Email playbook
        body: Hi from sayali 
        username: sayjoshi@redhat.com 
        password: {{password}}
        to: ahuchcha@redhat.com  
      #delegate_to: localhost
