---
- name: Sample Email Playbook  
  hosts: all
  tasks:
    - mail:
        host: localhost
        subject: Test Email playbook
        body: Hi from sayali
        from: sayjoshi@redhat.com 
        to: ahuchcha@redhat.com  
      #delegate_to: localhost
